name: learn_language
description: A Flutter application to help users learn english through interactive exercises and quizzes.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  google_mlkit_text_recognition: ^0.15.0
  flutter_tts: ^4.2.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4  
flutter:
  uses-material-design: true
  assets:
    - assets/words.json
    - assets/ranking.json
    - assets/sentences.json
    - assets/icon/
    - assets/icon/app_icon.png 

flutter_icons:
  android: true
  ios: true
  web: true
  image_path: "assets/icon/app_icon.png" 